project: HybridAI
timezone: America/Vancouver

trading_window:
  start: "05:00"   # 開盤時間
  end: "11:00"     # 收盤時間

risk:
  target_daily_return: 0.02
  max_daily_loss: 0.02
  max_position_risk: 0.01
  leverage:
    stocks: 2
    crypto: 3
    forex: 10

providers:
  polygon:
    api_key_env: dg9YCsmMS3FIAwsf1OkjnBX2xvelb3fX
  alpaca:
    key_id_env: PK66817E4JPYYI9BFVCR
    secret_key_env: Nc7j4BramB0SXWTsHd3UcieLfelxLdWIEorkRboV**

universe:
  Core_Stocks: [AAPL, MSFT, NVDA, TSLA, AMD, META, AMZN, GOOGL]
  Macro_Risk: [SPY, QQQ, DIA, VIXY, GLD, TLT]
  Crypto_Signal: [BTC.X, ETH.X, SOL.X, BNB.X]
  Leverage_Tools: [TQQQ, SQQQ, SOXL, SOXS, UVXY]
  IPO_Watch: [ARM, ABNB] # 視需要更新

features:
  enable_black_swan_guard: true
  enable_leverage_control: true
  enable_emotional_filter: true
  