from __future__ import annotations
from typing import Protocol, Any, Dict, Optional, Tuple, List

class Broker(Protocol):
    def connect(self) -> bool: ...
    def disconnect(self) -> None: ...
    def server_time(self) -> Optional[str]: ...
    def place_order(
        self,
        symbol: str,
        side: str,
        qty: float,
        order_type: str = "MARKET",
        limit_price: Optional[float] = None,
        meta: Optional[Dict[str, Any]] = None,
    ) -> Tuple[int, Dict[str, Any]]: ...
    def open_orders(self) -> List[Dict[str, Any]]: ...
    def positions(self) -> List[Dict[str, Any]]: ...