# DEPRECATED COPY  canonical config is config/config.yaml. This file is not read by SentimentFilter.
# Keep for archival only.

project: HybridAITrading (LIVE)

# ---------- RISK ----------
risk:
  equity: 100000
  max_drawdown: 0.15
  daily_loss_limit: -0.01      # -1% day breaker
  trade_loss_limit: -0.005     # -0.5%/trade
  roi_min: null
  sharpe_min: null
  sortino_min: null

# ---------- EXECUTION ----------
execution:
  use_paper_simulator: false   # LIVE routing
  costs:
    commission_pct: 0.0005
    slippage_pct: 0.0005
  # SmartOrderRouter expects these directly under 'execution'
  max_order_retries: 1
  timeout_sec: 5

# SmartOrderRouter reads alerts from top level ('alerts')
alerts:
  latency_threshold_ms: 500
  max_latency_breaches: 1

# ---------- REGIME DETECTOR ----------
regime:
  enabled: true
  method: hybrid
  lookback_days: 90
  bull_threshold: 0.02
  bear_threshold: -0.02
  crisis_volatility: 0.03
  min_samples: 60

# ---------- SENTIMENT ----------
# Disable to avoid extra gating & warnings unless you've installed vaderSentiment
sentiment:
  enabled: false
  model: vader
  threshold: 0.7
  neutral_zone: 0.2
  bias: none

# ---------- PROVIDER ENV VAR MAPPINGS ----------
# Ensures clients pick the right env var names
providers:
  polygon:
    api_key_env: POLYGON_KEY
  coinapi:
    api_key_env: COINAPI_KEY
