project: HybridAITrading (LIVE)
version: 7.2
timezone: America/Vancouver

# ---------- TRADING WINDOW (meta / for your reference) ----------
trading_window:
  start: "05:00"      # PT
  end:   "11:00"      # PT

# ---------- ENSEMBLE / GATESCORE (meta for strategy) ----------
gatescore:
  enabled: true
  threshold: 0.85
  adaptive: true
  models: [sentiment, price, macro, regime]
  weights:
    sentiment: 0.25
    price:     0.35
    macro:     0.25
    regime:    0.15

# ---------- RISK (runtime) ----------
risk:
  # Starting equity for risk manager
  equity: 100000

  # Hard equity-level stop
  max_drawdown: 0.20

  # Circuit breakers (mapped from your target/max loss)
  daily_loss_limit: -0.03       # from 'max_daily_loss: -0.03'
  trade_loss_limit: -0.005      # -0.5% per-trade veto

  # Optional performance guards (leave null to disable at start)
  roi_min: null
  sharpe_min: null
  sortino_min: null

# ---------- EXECUTION (runtime) ----------
execution:
  use_paper_simulator: false     # LIVE routing
  costs:
    # support both pct and per-share models used across modules
    commission_pct: 0.0005
    commission_per_share: 0.005
    min_commission: 1.00
    slippage_per_share: 0.01
  # SmartOrderRouter runtime knobs
  max_order_retries: 1
  timeout_sec: 5

# ---------- ALERTS (router reads this at top-level) ----------
alerts:
  latency_threshold_ms: 500
  max_latency_breaches: 1

# ---------- REGIME DETECTOR (runtime) ----------
regime:
  enabled: true
  method: hybrid
  lookback_days: 90
  bull_threshold: 0.02
  bear_threshold: -0.02
  crisis_volatility: 0.03
  min_samples: 60              # avoid 'auto' string; explicit int

# ---------- SENTIMENT (runtime) ----------
# Disable initially to avoid VADER/FinBERT warnings; enable after install
sentiment:
  enabled: false
  model: vader
  threshold: 0.8
  neutral_zone: 0.2
  bias: none
  smoothing: 3

# ---------- PROVIDERS (runtime mapping to env vars) ----------
providers:
  polygon:
    api_key_env: POLYGON_KEY
  coinapi:
    api_key_env: COINAPI_KEY
  alpaca:
    key_id_env: ALPACA_KEY_ID
    secret_key_env: ALPACA_SECRET_KEY
  benzinga:
    api_key_env: BENZINGA_KEY

# ---------- PORTFOLIO / UNIVERSE (meta for strategies) ----------
portfolio_choice: sharpe    # (meta) sharpe, minvol, equal, custom

custom_weights:             # (meta) used if portfolio_choice=custom
  BTC/USDT: 40
  ETH/USDT: 20
  SPY: 25
  GLD: 10
  TLT: 5

max_daily_shift: 0.2        # (meta)
order_type: market          # (meta)
slippage: 0.001             # (meta)

universe:
  Core_Stocks:   [AAPL, MSFT, GOOGL, AMZN, TSLA, NVDA, META, JPM, JNJ]
  Crypto_Signal: [BTC/USDT, ETH/USDT, SOL/USDT, BNB/USDT, XRP/USDT]
  Macro_Risk:    [SPY, QQQ, GLD, TLT, USO, UUP]
  Leverage_Tools:[TQQQ, SPXL, UVXY]
  IPO_Watch:     [ABNB, ARM, SNOW, RIVN, BIRK]

# ---------- FEATURE FLAGS (meta) ----------
features:
  enable_black_swan_guard: true
  enable_leverage_control: true
  enable_emotional_filter: true
  enable_multi_ai_signals: true
  enable_portfolio_guard: true
