project: HybridAITrading (LIVE)
version: 7.2
timezone: America/Vancouver

trading_window:
  start: "05:00"
  end: "11:00"

gatescore:
  enabled: true
  threshold: 0.85
  adaptive: true
  models:
    - sentiment
    - price
    - macro
    - regime
  weights:
    sentiment: 0.25
    price: 0.35
    macro: 0.25
    regime: 0.15

risk:
  equity: 100000
  max_drawdown: 0.20
  daily_loss_limit: -0.03
  trade_loss_limit: -0.005
  roi_min: null
  sharpe_min: null
  sortino_min: null

execution:
  use_paper_simulator: false
  costs:
    commission_pct: 0.0005
    commission_per_share: 0.005
    min_commission: 1.00
    slippage_per_share: 0.01
  max_order_retries: 1
  timeout_sec: 5

alerts:
  latency_threshold_ms: 500
  max_latency_breaches: 1

regime:
  enabled: true
  method: hybrid
  lookback_days: 90
  bull_threshold: 0.02
  bear_threshold: -0.02
  crisis_volatility: 0.03
  min_samples: 60

sentiment:
  enabled: false
  model: vader
  threshold: 0.8
  neutral_zone: 0.2
  bias: none
  smoothing: 3

providers:
  polygon:
    api_key_env: POLYGON_KEY
  coinapi:
    api_key_env: COINAPI_KEY
  alpaca:
    key_id_env: ALPACA_KEY_ID
    secret_key_env: ALPACA_SECRET_KEY
  benzinga:
    api_key_env: BENZINGA_KEY

portfolio_choice: sharpe

custom_weights:
  BTC/USDT: 40
  ETH/USDT: 20
  SPY: 25
  GLD: 10
  TLT: 5

max_daily_shift: 0.2
order_type: market
slippage: 0.001

universe:
  Core_Stocks:
    - AAPL
    - MSFT
    - GOOGL
    - AMZN
    - TSLA
    - NVDA
    - META
    - JPM
    - JNJ
  Crypto_Signal:
    - BTC/USDT
    - ETH/USDT
    - SOL/USDT
    - BNB/USDT
    - XRP/USDT
  Macro_Risk:
    - SPY
    - QQQ
    - GLD
    - TLT
    - USO
    - UUP
  Leverage_Tools:
    - TQQQ
    - SPXL
    - UVXY
  IPO_Watch:
    - ABNB
    - ARM
    - SNOW
    - RIVN
    - BIRK

features:
  enable_black_swan_guard: true
  enable_leverage_control: true
  enable_emotional_filter: true
  enable_multi_ai_signals: true
  enable_portfolio_guard: true
