# Hybrid AI Quant Pro — Paper Runner (micro-mode)
universe: ["AAPL","MSFT"]
mdt: 3               # 1=live,2=frozen,3=delayed,4=delayed-frozen
provider_only: false
prefer_providers: false
loop:
  sleep_sec: 5

risk_mgr: null       # plug your RiskManager object here when ready

# Optional model knobs (keep YAML strict; no tabs)
gatescore_min: 0.65
