project: HybridAI
timezone: America/Vancouver

trading_window:
  start: "05:00"    # 開盤時間 (Pacific 5 AM = 8 AM New York)
  end: "11:00"      # 收盤時間 (Pacific 11 AM = 2 PM New York)

risk:
  target_daily_return: 0.015   # 1.5% aggressive target (1–2% range)
  max_daily_loss: 0.02         # hard stop: max daily loss 2%
  max_position_risk: 0.01      # per-trade risk 1% of equity
  max_leverage: 10             # absolute cap (across all asset classes)

leverage:
  stocks: 2       # up to 2× leverage on equities
  crypto: 3       # up to 3× leverage on crypto
  forex: 10       # up to 10× leverage on forex
  ipo: 5          # up to 5× leverage on IPOs (high risk/high reward)

providers:
  polygon:
    api_key_env: POLYGON_KEY
  alpaca:
    key_id_env: ALPACA_KEY
    secret_key_env: ALPACA_SECRET
  coinapi:
    api_key_env: COINAPI_KEY
  benzinga:
    api_key_env: BENZINGA_KEY

universe:
  stocks: ["AAPL", "TSLA", "NVDA", "AMZN", "MSFT"]
  crypto: ["BTCUSD", "ETHUSD"]
  forex: ["EURUSD", "USDJPY"]
  ipo_watchlist: ["ARM", "KVYO", "CART"]  # Example IPO tickers

features:
  enable_black_swan_guard: true
  black_swan_sources:
    - "news_sentiment_ai"
    - "orderbook_anomaly_ai"
    - "macro_alert_ai"
  enable_multi_ai_signals: true
