name: ORB Smoke
on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: "20 2 * * *"   # daily @ 02:20 UTC
jobs:
  orb:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: python -V
      - run: python -m pip install -U pip
      - run: python -m pip install -r requirements-smoke.txt
      - name: Verify ORB hook present
        shell: pwsh
        run: |
          python -c "import io; t=io.open(r'src/hybrid_ai_trading/tools/bar_replay.py', encoding='utf-8').read(); assert 'setup=\"ORB\"' in t, 'ORB hook missing'; print('OK: ORB present')"

# ci: force fresh runner cache
